App\Model\Room:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 50
                minMessage: "Too short name, min length is: {{ limit }}"
                maxMessage: "Too long name, max length is: {{ limit }}"
        capacity:
            - NotBlank: ~
            - LessThan:
                value: 25
                message: "Maximum capacity of room is {{ compared_value }}"
            - GreaterThan:
                value: 2
                message: "Minimum capacity of room is {{ compared_value }}"
